### ISSUE TITLE
Could not compile on  1.54.0

### ISSUE THREAD

**Issue by Mart-Bogdan** [hopey-dishwasher/termpix#30]
```
   Compiling termpix v0.1.0 (/root/.cargo/git/checkouts/termpix-408ef1586b012b19/c22d061)
error[E0432]: unresolved import `image::FilterType`
 --> src/lib.rs:8:23
  |
8 | use image::{imageops, FilterType, Pixel};
  |                       ^^^^^^^^^^ no `FilterType` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: failed to compile `termpix v0.1.0 (https://github.com/hopey-dishwasher/termpix#c22d061f)`, intermediate artifacts can be found at `/tmp/cargo-install0LwvAX`

Caused by:
  could not compile `termpix`
```

rust version:  1.54.0. Ubuntu Linux. stable

**Comment by paperclipstudio** [comment]
I also have this issue on
rustc 1.52.1
Ubuntu on WSL2
when running 
`cargo install --git https://github.com/hopey-dishwasher/termpix;`

but by but downloading it via git and `cargo run some_pic.jpg` works fine

**Comment by paperclipstudio** [comment]
So its due to the unlocked version type for image in Cargo.toml 
The easy solution is just to fix the date to a older version orrrrr just update the code to work with the latest version which shouldn't be to hard so I'm going to work on that today.

**Comment by paperclipstudio** [comment]
#31
This should work now.

**Comment by GSY-PI** [comment]
Hi - As of today, I'm getting this issue when trying to compile using the link. I'm going to trying downloading directly like someone suggested to see if that works.

**Comment by GSY-PI** [comment]
> Hi - As of today, I'm getting this issue when trying to compile using the link. I'm going to trying downloading directly like someone suggested to see if that works.

UPDATE: Downloaded directly from the REPO. Appears when using 'cargo install' your get the issue, when using 'cargo build' then it builds and passes the check. (I always forget, cargo uses the build flag and so really discovered this by accident)
